# Generated by Django 3.0.3 on 2020-03-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id_shared', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
