# Generated by Django 3.0.3 on 2020-03-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20200318_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartes',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cartes',
            name='title',
            field=models.TextField(),
        ),
    ]
