# Generated by Django 3.0.3 on 2020-03-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0003_auto_20200318_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateField(auto_now=True)),
                ('review_level', models.IntegerField()),
                ('card_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='card.Cartes')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
